### PR TITLE
Use the `Node.Process` module

### PR DESCRIPTION
**Pull request by felixSchl**
* Re-use the existing effect definition from `Node.Process`, avoiding duplicate row labels
* ...and then also use the `Node.Process.exit` function instead of own function.

### CODE REVIEW

**Comment by owickstrom** [comment]
Thanks for the PR! It looks good on general, just an import in the tests that breaks the test build: https://travis-ci.org/owickstrom/purescript-spec/builds/117299254#L7237

**Comment by felixSchl** [comment]
My bad, should be sorted now.

**Comment by owickstrom** [comment]
Good job, thanks!

**Comment by felixSchl** [comment]
Any chance you could tag this for a release so I can depend on it?

**Comment by owickstrom** [comment]
Sure, my bad. Now tagged as `v0.7.4`.

**Comment by felixSchl** [comment]
Thanks!

**Pull request merged**
