### PR TITLE
Warn when using console reporter in browser environment

### PR DESCRIPTION
**Pull request by CRogers**
Unfortunately, I spent a lot of yesterday wondering why my tests wouldn't work when running my `purescript-spec` test suite via webpack, despite them working using `pulp test`. There were no errors to indicate what was going wrong, it just didn't print out any output. In the end I debugged the resulting javascript and found it was because `purescript-spec` checks for the existence of `process.stdout.write` and will not print anything if it doesn't exist. In the end I just needed to change my webpack config to `target: 'node'`. However, the silent failure of the test suite is still unfortunate; to help people in the future I've made this PR that will print out a warning about `process.stdout.write` not existing if they try to run it in a bad environment, with some recommendations about how to fix it.

### CODE REVIEW

**Comment by owickstrom** [comment]
Ah, I'm sorry that you had trouble with this!

Actually the `process.stdout.write` is just there to be able to write escape sequences and get colored output. If it's not available then the Console module should just ignore calls to `setAttr`. The annoying part is `write` which prints to the console without a trailing newline, there's no console equivalent AFAIK. If the console reporter uses `write` to do some strange stuff it's OK if we just change the format slightly where needed.

I suggest we:
* Remove `write`.
* Keep `writeln` but use `console.log` internally instead.
* Check for `process.stdout.write` availability in the `setAttr` function and do nothing if it's unavailable.
* Rewrite the console reporter.

Does this seem OK? Is it something you'd be willing to change in your PR?

Thanks for contributing to purescript-spec!

**Comment by CRogers** [comment]
Sounds good to me, I'll make the changes if I have time once I get home from work.

**Comment by CRogers** [comment]
Ok, I've made the changes you suggested.

**Comment by owickstrom** [comment]
Replaced `consoleLog` with `log` from purescript-console. Everything looks great, thanks for your contribution!

**Pull request merged**
