### PR TITLE
Fix #55

### LINKED ISSUE #55: Node.Process
The Node.Process dependency is placing a hard dependency where you have to run the tests on nodejs. The issue with that is that you can't use something like phantomjs to run tests and test libraries that interact with the DOM.

How do you feel about going back to defining a custom PROCESS effect?

### PR DESCRIPTION
**Pull request by Risto-Stevcev**
Fixes #55

### CODE REVIEW

**Comment by Risto-Stevcev** [comment]
It works :) I tested the PR with this:
https://gist.github.com/Risto-Stevcev/4ad38dcd812bbdc905832b9558ae8ea3

**Comment by owickstrom** [comment]
Works for me as well!

I noticed that `purescripts/purescript-phantom` has an `exit` function, bound to `phantom.exit` in JS. What do you say we check for that in purescript-spec as well, and exit with it if available?

**Comment by owickstrom** [comment]
Thank you for your contribution!

**Comment by Risto-Stevcev** [comment]
np :slightly_smiling_face:

**Pull request merged**
