### PR TITLE
PureScript 0.7 Compatibility

### PR DESCRIPTION
**Pull request by DavidHarrison**
[Changes for PureScript 0.7 compatibility](https://github.com/purescript/purescript/wiki/0.7-Migration-Guide), explicit imports and tweaks for compatibility with [pulp](https://github.com/bodil/pulp):
- Update dependencies in bower.json
- Move foreign functions into separate files
- Change `[a]` types to `Array a`
- Replace Array cons patterns with folds
- Remove some helper functions that are now in (relatively standard) libraries on bower
- Move `tests` to `test` (for pulp)
- Generate documentation with pulp

All of the tests seem to run correctly.

### CODE REVIEW

**Comment by owickstrom** [comment]
@DavidHarrison On vacation right now but I'll have a look at this ASAP. Thanks!

#11

**Comment by DavidHarrison** [comment]
Thank you. Have a great vacation!

**Comment by owickstrom** [comment]
Thank you for your contribution! Added some fixes to get the Makefile working again, but also tried it with pulp and that works fine. Looks really good, thanks again!

**Comment by DavidHarrison** [comment]
Thank you!

**Pull request merged**
