### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by anttih**
Use `Pattern` where required and fix one warning in tests.

### CODE REVIEW

**Comment by owickstrom** [comment]
Looks great, thanks! I removed an unused import that caused a warning, but that was it.

**Comment by owickstrom** [comment]
I've released a new version that you can depend on: https://pursuit.purescript.org/packages/purescript-spec/0.9.1

**Comment by anttih** [comment]
Thanks! One thing though, I think the requirement for a new compiler version would warrant a new major release, that is 1.0.0.

**Comment by owickstrom** [comment]
Following semantic versioning, I think all 0.x minor releases are allowed to be backwards-incompatible, and not until you've started at 1.x that you need to bump the major version when breaking compatibility. I may have misunderstood this, or maybe regular semantic versioning is not the convention in the PureScript community. If so, please correct me. :)

**Comment by owickstrom** [comment]
However, maybe it's time to bring this project up to 1.0.0. I did push a rather big change just now, and released 0.10.0, but the API is more or less the same for users. In the future I do not think the API will change drastically. I want to add filtering of tests and fix some bug in the console reporter, but that's about it for now.

**Comment by anttih** [comment]
Sounds good!

**Pull request merged**
